lint:
  rules:
    remove:
      - MAX_LINE_LENGTH
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - ENUM_FIELD_NAMES_START_WITH_UPPER_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
