[package]
name = "snitch-detective"
version = "0.0.1"
edition = "2021"

[dependencies]
ajson = "0.3.1"
chrono = "0.4.26"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.19"
protobuf = "3.2.0"
protobuf-json-mapping = "3.2.0"
regex = "1.8.4"
snitch-protos = "0.0.9"
thiserror = "1.0.40"
