version: '3'

services:
  web:
    build: .
    container_name: snitch-console-container
    image: snitch-console-image
    environment:
      - SNITCH_GRPC_WEB_URL="http://127.0.0.1:9091"
    ports:
      - "3000:3000"
