version: "3"
services:
  snitch-server:
    image: streamdal/snitch-server:latest
#    build:
#      context: ./
#      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - SNITCH_SERVER_NODE_NAME=node1
      - SNITCH_SERVER_AUTH_TOKEN=1234
      - SNITCH_SERVER_REDIS_URL=redis:6379
      - SNITCH_SERVER_DEBUG=true
    container_name: snitch-server
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - snitch-network

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --appendonly yes # This enables AOF persistence
    volumes:
      - redis-data:/data # Persist redis data to this volume
    ports:
      - "6379:6379"
    networks:
      - snitch-network

  envoy:
    build:
      context: ${PWD}/assets/envoy
      dockerfile: ${PWD}/assets/envoy/Dockerfile
    image: grpcweb/envoy
    container_name: snitch-envoy
    ports:
      - "9091:9091"
    networks:
      - snitch-network

volumes:
  redis-data: # Define the volume for redis data

networks:
  snitch-network: