name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Test
        run: |
          make test

      - name: Build
        run: |
          make build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/streamdal*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
