name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.5
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Zip Project
        run: zip -r ${GITHUB_REPOSITORY#*/}.zip .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Copying repository zipfile to AWS S3
        run: |
          aws s3 cp ${GITHUB_REPOSITORY#*/}.zip s3://${{ secrets.AWS_S3_ARCHIVE_BUCKET }}/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}.zip

  batch_push:
    runs-on: ubuntu-latest
    name: Update protobuf schema in Batch
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push new schemas engineering prod
        uses: batchcorp/schema-publisher@v3
        id: publish-1
        env:
          STREAMDAL_API_TOKEN: '${{ secrets.BATCH_API_TOKEN }}'
          STREAMDAL_SCHEMA_ID: '0c9e36da-b5f4-4f0c-8d36-bd25f72866d2'
          STREAMDAL_SCHEMA_NAME: '${{ github.repository }}: ${{ needs.build.outputs.new_tag }}'
          STREAMDAL_SCHEMA_TYPE: 'protobuf'
          STREAMDAL_INPUT: 'build/protoset/events.protoset'
          STREAMDAL_INPUT_TYPE: 'descriptor_set'
          STREAMDAL_API_ADDRESS: 'https://api.streamdal.com'
          STREAMDAL_DEBUG: true
      - name: Push new schemas demo dev
        uses: batchcorp/schema-publisher@v3
        id: publish-2
        env:
          STREAMDAL_API_TOKEN: '${{ secrets.BATCH_DEMO_API_TOKEN }}'
          STREAMDAL_SCHEMA_ID: '4e6d0fc2-c160-4189-9f3f-72c43785c450'
          STREAMDAL_SCHEMA_NAME: '${{ github.repository }}: ${{ needs.build.outputs.new_tag }}'
          STREAMDAL_SCHEMA_TYPE: 'protobuf'
          STREAMDAL_INPUT: 'build/protoset/fakes.protoset'
          STREAMDAL_INPUT_TYPE: 'descriptor_set'
          STREAMDAL_API_ADDRESS: 'https://api.dev.streamdal.com'
          STREAMDAL_DEBUG: true
