name: Wasm-Detective - Release

on:
  push:
    branches:
      - main
    paths:
      - 'libs/wasm-detective/**'
      - '.github/workflows/libs-wasm-detective-release.yml'

defaults:
  run:
    working-directory: ./libs/wasm-detective

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@main

      - name: Generate new tag (dry run)
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: "libs/wasm-detective/v"

      - name: Update Cargo.toml version
        run: |
          pwd
          ls -l
          sed -i "s/version = \".*\"/version = \"${{ steps.get_new_version.outputs.new_version }}\"/" Cargo.toml
          grep version Cargo.toml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumped Cargo.toml version to ${{ steps.get_new_version.outputs.new_version }}

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "libs/wasm-detective/v"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Release on crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path libs/wasm-detective/Cargo.toml --token ${{ secrets.CRATES_IO_TOKEN }}
