name: Protos - Release

on:
  push:
    branches:
      - main
    paths:
      - 'libs/protos/**'

defaults:
  run:
    working-directory: ./libs/protos

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/streamdal-protos
    steps:
      - uses: actions/checkout@main
      - name: Generate new tag (dry run)
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: "protos/v"
      - name: Update Cargo.toml version
        run: |
          pwd
          ls -l
          sed -i "s/version = \".*\"/version = \"${{ steps.get_new_version.outputs.new_version }}\"/" build/rust/protos/Cargo.toml
          grep version build/rust/protos/Cargo.toml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumped Cargo.toml version to ${{ steps.get_new_version.outputs.new_version }}
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "protos/v"
      - name: Release on crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          # need full path because "working-directory" is used only for "run" steps
          args: --manifest-path libs/protos/build/rust/protos/Cargo.toml --token ${{ secrets.CRATES_IO_TOKEN }} --locked
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Release on npm
        working-directory: ./build/ts/node
        run: |
          npm version ${{ steps.get_new_version.outputs.new_version }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build python dist
        run: |
          cd build/python
          sed -i "s/version=.*/version='${{ steps.get_new_version.outputs.new_version }}',/" setup.py
          python3 setup.py sdist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: libs/protos/build/python/dist
          password: ${{ secrets.PYPI_API_TOKEN }}
