name: Test main
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '~1.18'
      - uses: actions/checkout@master
      - name: Start up dependencies
        run: docker-compose -f docker-compose.dev.yaml up -d redis
      - name: Wait for dependencies to start up
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Main build tests
        run: |
          sudo make test
