name: Build master
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '~1.18'
      - uses: actions/checkout@master
      - name: Start up dependencies
        run: docker-compose -f docker-compose.dev.yaml up -d natsjs
      - name: Wait for dependencies to start up
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Master buld tests
        run: |
          sudo make test

  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@master
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.CR_PAT }}
      - name: Run build & push
        run: |
          make docker/build
          make docker/push
