on: pull_request
name: Pull Request
jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          rustup target add wasm32-wasi
          cargo install wasm-opt
          make build