on: pull_request
name: Pull Request
jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        funcs: ["detective", "httprequest", "inferschema", "kv", "transform", "validjson"]
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: build
        run: |
          rustup target add wasm32-wasi
          cargo install wasm-opt
          make build

      - name: modsurfer validate
        uses: dylibso/modsurfer-validate-action@main
        with:
            path: build/${{ matrix.funcs }}.wasm
            check: validation/${{ matrix.funcs }}/mod.yaml