on: pull_request
name: Pull Request

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest  # You can choose other OS options if needed

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any specific requirements for your project

      - name: Run Pytest
        run: |
          make test/wasm
          pytest

  pypi-publish:
    needs: python-build-dist
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Build python dist
        run: |
          cd build/python
#          sed -i "s/version=\".*\"/version=\"${{ steps.get_new_version.outputs.new_version }}\"/" snitchpy/__init__.py
#          sed -i "s/version=.*/version='${{ steps.get_new_version.outputs.new_version }}',/" setup.py
          python3 setup.py sdist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/