on: pull_request
name: Pull Request
jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: build
        run: |
          rustup target add wasm32-wasi
          cargo install wasm-opt
          make build
